local characters = {
    krieger = {
        ["Sir Valadir"] = {
            bewegung = 4,
            lebenskraft = 12,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 4,
            staerke = 3,
            wissen = 3,
            geistesgegenwart = 1,

        },
        ["Einfaust"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 3,
            wissen = 2,
            geistesgegenwart = 3,
        },
        ["Mordog"] = {
            bewegung = 4,
            lebenskraft = 14,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 5,
            wissen = 1,
            geistesgegenwart = 2,
        },
        ["Karnon"] = {
            bewegung = 4,
            lebenskraft = 14,
            ausdauer = 3,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 6,
            wissen = 1,
            geistesgegenwart = 2,
        },
        ["Grisban der Durstige"] = {
            bewegung = 3,
            lebenskraft = 14,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 5,
            wissen = 2,
            geistesgegenwart = 1,
        },
        ["Tahlia"] = {
            bewegung = 3,
            lebenskraft = 14,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 3,
            wissen = 2,
            geistesgegenwart = 3,
        },
        ["Kundschafter Durik"] = {
            bewegung = 5,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 3,
            wissen = 2,
            geistesgegenwart = 4,
        },
        ["Reynhart der Erhabene"] = {
            bewegung = 4,
            lebenskraft = 12,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 4,
            staerke = 3,
            wissen = 1,
            geistesgegenwart = 3,
        },
        ["Krutzbeck"] = {
            bewegung = 3,
            lebenskraft = 12,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 4,
            wissen = 2,
            geistesgegenwart = 2,
        },
        ["Orkell der Flinke"] = {
            bewegung = 5,
            lebenskraft = 10,
            ausdauer = 5,
            verteidigung = "braun",

            willenskraft = 2,
            staerke = 4,
            wissen = 1,
            geistesgegenwart = 4,
        },
        ["Stahlhorn"] = {
            bewegung = 4,
            lebenskraft = 14,
            ausdauer = 3,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 5,
            wissen = 1,
            geistesgegenwart = 2,
        },
        ["Corbin"] = {
            bewegung = 3,
            lebenskraft = 12,
            ausdauer = 5,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 5,
            wissen = 2,
            geistesgegenwart = 2,
        },
        ["Nanok die Klinge"] = {
            bewegung = 4,
            lebenskraft = 12,
            ausdauer = 4,
            verteidigung = "schwarz",

            willenskraft = 2,
            staerke = 4,
            wissen = 2,
            geistesgegenwart = 3,
        },
        ["Lord Hawthorne"] = {
            bewegung = 4,
            lebenskraft = 12,
            ausdauer = 3,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 4,
            wissen = 3,
            geistesgegenwart = 2,
        },
        ["Alice Raine"] = {
            bewegung = 4,
            lebenskraft = 12,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 2,
            wissen = 4,
            geistesgegenwart = 1,

        },
        ["Trenloe der Starke"] = {
            bewegung = 3,
            lebenskraft = 12,
            ausdauer = 3,
            verteidigung = "grau",

            willenskraft = 4,
            staerke = 4,
            wissen = 1,
            geistesgegenwart = 2,
        },
        ["Nara der Reiszahn"] = {
            bewegung = 5,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 4,
            wissen = 1,
            geistesgegenwart = 4,
        },
    },
    magier = {
        ["Ravaella Leichtfuss"] = {
            bewegung = 4,
            lebenskraft = 8,
            ausdauer = 5,
            verteidigung = "schwarz",

            willenskraft = 2,
            staerke = 1,
            wissen = 4,
            geistesgegenwart = 4,
        },
        ["Challara"] = {
            bewegung = 3,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 3,
            wissen = 4,
            geistesgegenwart = 1,
        },
        ["Jaes der Verbrannte"] = {
            bewegung = 4,
            lebenskraft = 12,
            ausdauer = 3,
            verteidigung = "grau",

            willenskraft =2,
            staerke = 3,
            wissen = 4,
            geistesgegenwart = 2,
        },
        ["Shiver"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 2,
            wissen = 3,
            geistesgegenwart = 3,
        },
        ["Zyla"] = {
            bewegung = 5,
            lebenskraft = 8,
            ausdauer = 5,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 1,
            wissen = 4,
            geistesgegenwart = 3,
        },
        ["Lyssa"] = {
            bewegung = 5,
            lebenskraft = 8,
            ausdauer = 5,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 2,
            wissen = 3,
            geistesgegenwart = 4,
        },
        ["Grossmagier Cwellin"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 1,
            wissen = 5,
            geistesgegenwart = 2,
        },
        ["Desra die Schändliche"] = {
            bewegung = 5,
            lebenskraft = 8,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 2,
            wissen = 4,
            geistesgegenwart = 3,
        },
        ["Astara"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 5,
            verteidigung = "grau",

            willenskraft = 4,
            staerke = 1,
            wissen = 4,
            geistesgegenwart = 2,
        },
        ["Andira Runenhand"] = {
            bewegung = 4,
            lebenskraft = 12,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 4,
            staerke = 2,
            wissen = 3,
            geistesgegenwart = 2,
        },
        ["Leorik der Gelehrte"] = {
            bewegung = 4,
            lebenskraft = 8,
            ausdauer = 5,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 1,
            wissen = 5,
            geistesgegenwart = 3,
        },
        ["Sehering Kel"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 1,
            wissen = 4,
            geistesgegenwart = 4,
        },
    },
    kundschafter = {
        ["Tetherys"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 1,
            staerke = 3,
            wissen = 2,
            geistesgegenwart = 5,
        },
        ["Raythen"] = {
            bewegung = 4,
            lebenskraft = 14,
            ausdauer = 4,
            verteidigung = "braun",

            willenskraft = 1,
            staerke = 3,
            wissen = 2,
            geistesgegenwart = 5,
        },
        ["Vyrah der Falkner"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 3,
            wissen = 2,
            geistesgegenwart = 4,
        },
        ["Logan Lashley"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 3,
            wissen = 2,
            geistesgegenwart = 4,
        },
        ["Arvel WEltenwanderer"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 3,
            wissen = 3,
            geistesgegenwart = 3,
        },
        ["Thaiden Nebelspitze"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 5,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 3,
            wissen = 1,
            geistesgegenwart = 5,
        },
        ["Silhouette"] = {
            bewegung = 5,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 1,
            staerke = 3,
            wissen = 2,
            geistesgegenwart = 5,
        },
        ["Roganna der Schemen"] = {
            bewegung = 5,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 4,
            staerke = 2,
            wissen = 2,
            geistesgegenwart = 3,
        },
        ["Ker der Graue"] = {
            bewegung = 4,
            lebenskraft = 12,
            ausdauer = 5,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 3,
            wissen = 2,
            geistesgegenwart = 4,
        },
        ["Lindel"] = {
            bewegung = 5,
            lebenskraft = 10,
            ausdauer = 5,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 3,
            wissen = 3,
            geistesgegenwart = 3,
        },
        ["Jaine Fairwood"] = {
            bewegung = 5,
            lebenskraft = 8,
            ausdauer = 5,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 2,
            wissen = 3,
            geistesgegenwart = 4,
        },
        ["Laurel vom Blutwald"] = {
            bewegung = 4,
            lebenskraft = 8,
            ausdauer = 5,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 2,
            wissen = 3,
            geistesgegenwart = 4,
        },
        ["Tinashi die Wanderin"] = {
            bewegung = 4,
            lebenskraft = 12,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 3,
            wissen = 2,
            geistesgegenwart = 3,
        },
        ["Tatianna"] = {
            bewegung = 5,
            lebenskraft = 12,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 2,
            staerke = 2,
            wissen = 2,
            geistesgegenwart = 5,
        },
        ["Ronan der Wilde"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 5,
            verteidigung = "grau",

            willenskraft = 4,
            staerke = 3,
            wissen = 1,
            geistesgegenwart = 3,
        },
    },
    heiler = {
        ["Sahla"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 2,
            wissen = 3,
            geistesgegenwart = 3,
        },
        ["Augur Grisom"] = {
            bewegung = 3,
            lebenskraft = 12,
            ausdauer = 5,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 4,
            wissen = 2,
            geistesgegenwart = 2,
        },
        ["Geistersprecher Mok"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 4,
            staerke = 2,
            wissen = 3,
            geistesgegenwart = 2,
        },
        ["Jonas der Gütige"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 4,
            staerke = 2,
            wissen = 3,
            geistesgegenwart = 2,
        },
        ["Ulma Grimstone"] = {
            bewegung = 4,
            lebenskraft = 8,
            ausdauer = 5,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 2,
            wissen = 4,
            geistesgegenwart = 2,
        },
        ["Ispher"] = {
            bewegung = 4,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 2,
            wissen = 3,
            geistesgegenwart = 3,
        },
        ["Rendiel"] = {
            bewegung = 5,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 5,
            staerke = 2,
            wissen = 3,
            geistesgegenwart = 1,
        },
        ["Ashrian"] = {
            bewegung = 5,
            lebenskraft = 10,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 2,
            wissen = 2,
            geistesgegenwart = 4,
        },
        ["Okaluk und Rakash"] = {
            bewegung = 2,
            lebenskraft = 8,
            ausdauer = 3,
            verteidigung = "grau",

            willenskraft = 3,
            staerke = 3,
            wissen = 2,
            geistesgegenwart = 3,
        },
        ["Serena"] = {
            bewegung = 3,
            lebenskraft = 8,
            ausdauer = 6,
            verteidigung = "braun",

            willenskraft = 5,
            staerke = 1,
            wissen = 3,
            geistesgegenwart = 2,
        },
        ["Bruder Gherinn"] = {
            bewegung = 3,
            lebenskraft = 12,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 4,
            staerke = 1,
            wissen = 4,
            geistesgegenwart = 2,
        },
        ["Avric Albright"] = {
            bewegung = 4,
            lebenskraft = 12,
            ausdauer = 4,
            verteidigung = "grau",

            willenskraft = 4,
            staerke = 2,
            wissen = 3,
            geistesgegenwart = 2,
        },
    }
}